---
name: Coverage
description: Test coverage
inputs:
  plugin:
    description: Name of the plugin to build
    required: true
    default: ""
  node-version:
    description: Node.js version
    required: true
    default: 20
env:
  codecov:
    description: Codecov token
    required: true
    default: ""
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup for Turbo cache
      uses: dtinth/setup-github-actions-caching-for-turbo@a0e976d970c2a94366a26984efcef3030e2c0115 # v1

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.plugin }}
      run: |
        npm install -g yarn
        npm install -g nyc
        yarn install
        if [[ $(git diff --name-only . || true) ]]; then
          echo "After 'yarn install', workspace is dirty! The following files have changed:"
          echo
          git diff --name-only . || true
          exit 42
        fi

    - name: Run tests and generate coverage report
      shell: bash
      working-directory: ${{ inputs.plugin }}
      run: |
        yarn test --coverage
        nyc report --reporter html --reporter text -t coverage --report-dir coverage/summary

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ env.codecov }}
      with:
        # token: ${{ env.codecov }}
        use_oidc: true
        file: ./${{ inputs.plugin }}/coverage/lcov.info
        fail_ci_if_error: true
        verbose: true
