FROM scratch

# Copy dynamic plugins
COPY . .

# Required labels for Red Hat certification
LABEL name="ansible-backstage-plugins" \
      vendor="Red Hat, Inc." \
      version="2.0.1" \
      release="1" \
      summary="Red Hat Developer Hub Ansible Backstage Dynamic Plugins" \
      description="Dynamic plugins collection for Red Hat Developer Hub (RHDH) providing Ansible automation capabilities, authentication, catalog management, and scaffolding functionality." \
      maintainer="Red Hat Ansible Team <ansible-team@redhat.com>" \
      io.k8s.description="Red Hat Developer Hub Ansible Backstage Dynamic Plugins" \
      io.k8s.display-name="RHDH Ansible Dynamic Plugins" \
      io.openshift.tags="ansible,backstage,rhdh,automation,dynamic-plugins" \
      com.redhat.component="ansible-backstage-plugins" \
      distribution-scope="public" \
      url="https://github.com/ansible/ansible-backstage-plugins/" \
      vcs-ref="main" \
      vcs-type="git" \
      cpe="cpe:/a:redhat:ansible_portal:2.0::el9" \
      org.opencontainers.image.created="${SOURCE_DATE_EPOCH}"

# Add license information for certification compliance
COPY LICENSE /licenses/

# Switch to non-root user for security compliance
USER 1001
